### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by ivancevich** [davej/angular-classy#38]
I think Angular Classy is a pretty cool project. I've been working with Angular a lot, and this seems to make things quite easier.
Could you publish Classy on NPM, so I can use it using CommonJS and Browserify?
Also I'd like to know if the 1.0 beta is stable enough to use in production.
Thanks!

**Comment by davej** [comment]
I've had more of a think about this and I've decided that I will stay away from module definition schemes for the moment but I'm happy to take pull requests from people requiring this functionality. I'm also happy to help people come up with a nice shim for their chosen module definition spec.

Classy is a bit different than your average module because it monkey-patches the `angular.module` function. It's not so simple to come up with a one-size-fits-all UMD but I'm happy to help anybody who wants to give it a shot.

**Comment by davej** [comment]
Published to npm in [`v1.2.4`](https://github.com/davej/angular-classy/releases/tag/v1.2.4).
